services:
  - type: web
    name: sky-cadastral
    env: node
    rootDir: SkyCadastralAdmin/Admin/Backend
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
